---
title: "Introduction to Data Analysis using R"
author: "Dmytro Rybalko"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
#github-repo: rstudio/bookdown-demo
description: "Here is present my expirience in data analysis and visualizatioin in R of using the bookdown package to write a book"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 9,
  fig.height = 7)
```

# Intro

Here is present my expirience in data analysis and visualization using R based on course [Analyzing and Visualizing Data With Excel](https://www.edx.org/course/analyzing-and-visualizing-data-with-excel).

I solved tasks from this course with next packages and libraries:  
- manipualation and trasformation data using [dplyr](https://dplyr.tidyverse.org/) and [tidyr](https://tidyr.tidyverse.org/) libraries from [tidyverse](https://www.tidyverse.org/) package;  
- data visualization with [ggplot2](https://ggplot2.tidyverse.org/) library;  
- make excel-like readable reports with conditional formatting (color, icons, sparklines) using [formattable](https://github.com/renkun-ken/formattable), [sparklines](https://github.com/htmlwidgets/sparkline), [htmlwidgets](https://www.htmlwidgets.org/);  
- and finaly use [bookdown](https://bookdown.org/yihui/bookdown/) for creating technical documents (like this) with [R markdown](https://rmarkdown.rstudio.com/).  
  
Solving the objectives of this course helped me better understand how to convert data for further analysis, how to create pretty good and informative charts and tables. Hope you can find something useful for yourself as you browse through this work :)
